// Expo config plugin: wire the Android release build to our upload keystore.
//
// The android/ folder is generated by `expo prebuild` (CNG) and gitignored, so
// a signing config can't live there durably. This plugin re-injects it into
// android/app/build.gradle on every prebuild.
//
// Secrets are NOT stored here or anywhere in the repo. They come from Gradle
// properties:
//   - CI: the release workflow appends them to android/gradle.properties from
//     repo secrets (see .github/workflows/release-mobile.yml).
//   - Local: put them in ~/.gradle/gradle.properties (outside the repo):
//       POCKET_MONEY_UPLOAD_STORE_FILE=/abs/path/to/upload.keystore
//       POCKET_MONEY_UPLOAD_STORE_PASSWORD=...
//       POCKET_MONEY_UPLOAD_KEY_ALIAS=pocket-money-upload
//       POCKET_MONEY_UPLOAD_KEY_PASSWORD=...
//
// When those properties are absent (e.g. a fresh clone with no key), the
// release build falls back to debug signing exactly like the stock Expo
// template, so `prebuild` and debug builds keep working for anyone.

const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = 'POCKET_MONEY_UPLOAD_STORE_FILE';

const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('POCKET_MONEY_UPLOAD_STORE_FILE')) {
                storeFile file(project.property('POCKET_MONEY_UPLOAD_STORE_FILE'))
                storePassword project.property('POCKET_MONEY_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('POCKET_MONEY_UPLOAD_KEY_ALIAS')
                keyPassword project.property('POCKET_MONEY_UPLOAD_KEY_PASSWORD')
            }
        }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy build.gradle');
    }
    let gradle = config.modResults.contents;

    if (gradle.includes(MARKER)) {
      return config; // already patched (idempotent)
    }

    // 1. Add a `release` signingConfig right after the existing `debug` one.
    const beforeSigning = gradle;
    gradle = gradle.replace(
      /(signingConfigs\s*\{\s*debug\s*\{[\s\S]*?\}\s*)\}/,
      `$1${RELEASE_SIGNING_CONFIG}\n    }`
    );
    if (gradle === beforeSigning) {
      throw new Error(
        'withReleaseSigning: could not find signingConfigs { debug { ... } } to extend'
      );
    }

    // 2. Point the release buildType at signingConfigs.release when the key
    //    exists, otherwise keep debug signing (stock fallback).
    const beforeBuildTypes = gradle;
    gradle = gradle.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[^}]*?)signingConfig signingConfigs\.debug/,
      `$1signingConfig project.hasProperty('POCKET_MONEY_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`
    );
    if (gradle === beforeBuildTypes) {
      throw new Error(
        'withReleaseSigning: could not find release buildType signingConfig to redirect'
      );
    }

    config.modResults.contents = gradle;
    return config;
  });
};
