/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and returns a JWT plus the user, so the client is logged in immediately (auto-login). Same response shape as login; no separate login call is needed after registering.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Authenticates a user and returns a JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the currently authenticated user's information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password (logged-in)
         * @description Changes the authenticated user's password. Verifies the current password (bcrypt) before setting the new one. No email/reset flow. Does NOT rotate the JWT — existing tokens remain valid until expiry (LAN v2 limitation).
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's groups
         * @description Returns all groups the authenticated user is a member of
         */
        get: operations["listGroups"];
        put?: never;
        /**
         * Create a new group
         * @description Creates a new group with the authenticated user as admin
         */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get group details
         * @description Returns detailed information about a group including members and chores count
         */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List group members
         * @description Returns all members of a group
         */
        get: operations["listMembers"];
        put?: never;
        /**
         * Add a member by email (add-by-email lifecycle)
         * @description Admin-only. Resolves the email to a user and attaches them to the group as a `member`: an unknown email creates a new SHADOW user (no password, cannot log in) with the given name; an existing registered user is attached and notified (N-1 `added_to_group`); an existing shadow is attached with no notification. Adding the same email to the same group again is a `409` (exactly one membership, at most one N-1 from the first successful add).
         */
        post: operations["addMemberByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member (admin) or leave a group (self)
         * @description Removes a membership. The admin may remove any non-admin member; any member may remove themselves (leave). Allowed ONLY when the target member's balance is settled to exactly 0 AND they have no loan in `requested` or `active` status. Ledger history and closed/rejected loans are KEPT (they reference the user, not the membership); the member's allowance config rows are deleted and any pending ledger entries are auto-rejected. The group admin can neither leave nor be removed. Triggers due allowance/EMI posting before evaluating the balance so a stale un-posted entry cannot let a non-zero member out.
         */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create group invite
         * @description Creates an invite token for joining the group (admin only)
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join group
         * @description Joins a group using an invite token
         */
        post: operations["joinGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/chores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chores
         * @description Returns all chores for a group
         */
        get: operations["listChores"];
        put?: never;
        /**
         * Create chore
         * @description Creates a new chore for the group (admin only)
         */
        post: operations["createChore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete chore
         * @description Soft deletes a chore (admin only)
         */
        delete: operations["deleteChore"];
        options?: never;
        head?: never;
        /**
         * Update chore
         * @description Updates a chore (admin only)
         */
        patch: operations["updateChore"];
        trace?: never;
    };
    "/api/v1/groups/{id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ledger entries
         * @description Returns ledger entries for a group. Members see only their own entries; admin sees all. A member supplying `user_id` for another member gets 403 (D6) — they may only scope to themselves.
         */
        get: operations["listLedger"];
        put?: never;
        /**
         * Create ledger entry
         * @description Creates a new ledger entry. Members create pending entries for themselves, admin can create approved entries for any member.
         */
        post: operations["createLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve ledger entry
         * @description Approves a pending ledger entry (admin only)
         */
        post: operations["approveLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject ledger entry
         * @description Rejects a pending ledger entry (admin only)
         */
        post: operations["rejectLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get group balances
         * @description Admin sees every member's balance; a member sees only their own balance row (D6).
         */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/allowances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List allowance rows for a group
         * @description Admin sees all members' allowance history; member sees only their own. Returns full history rows (all effective_from values per member).
         */
        get: operations["listAllowances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/allowances/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or change a member's monthly pocket money
         * @description Admin only. Sets or changes a member's monthly pocket money. A new effective_from creates a new history row (past months not rewritten). Amount 0 pauses the allowance. Setting the same effective_from twice updates the amount (correction) — idempotent, still 200.
         */
        put: operations["setAllowance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List loans for a group
         * @description Admin sees all loans; member sees only their own. A member supplying `user_id` for another member gets 403 (D6) — they may only scope to themselves.
         */
        get: operations["listLoans"];
        put?: never;
        /**
         * Create a loan or loan request
         * @description Member creates a `requested` loan for themselves; admin creates a pre-approved `active` loan for a member. Disbursement is not a ledger entry; repayment is via monthly EMI debits.
         */
        post: operations["createLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a loan request
         * @description Admin only. Transitions `requested` → `active`; may override principal/installments; sets start_period to next calendar month.
         */
        post: operations["approveLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a loan request
         * @description Admin only. Transitions `requested` → `rejected`.
         */
        post: operations["rejectLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Early payoff — close an active loan
         * @description Admin only. Posts one final EMI debit for the outstanding amount (principal − Σ posted EMIs) and sets status to `closed`.
         */
        post: operations["closeLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description User's password (minimum 6 characters) */
            password: string;
            /** @description User's full name */
            name: string;
            /**
             * Format: date
             * @description Date of birth (YYYY-MM-DD)
             */
            dob?: string | null;
            /** @description User's sex */
            sex?: string | null;
        };
        ChangePasswordRequest: {
            /** @description The user's current password, verified before the change. */
            current_password: string;
            /** @description The new password (minimum 6 characters). */
            new_password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description User's password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT authentication token */
            token: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /**
             * Format: uuid
             * @description User ID
             */
            id: string;
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description User's full name */
            name: string;
            /**
             * @description Account status. A logged-in user is always `registered` (shadow users cannot authenticate); exposed for completeness/consistency.
             * @enum {string}
             */
            status: "shadow" | "registered";
            /**
             * Format: date-time
             * @description Date of birth
             */
            dob?: string | null;
            /** @description User's sex */
            sex?: string | null;
            /**
             * Format: date-time
             * @description Account creation timestamp
             */
            created_at: string;
        };
        /** @description A monetary amount in a group's currency. `value` is in minor units (cents/paise; all three supported currencies have exponent 2) and is NEVER a float. `currency` always equals the owning group's currency (D7); the server rejects any request whose currency differs from the group's. */
        Money: {
            /**
             * @description ISO-4217 code; always the owning group's currency.
             * @enum {string}
             */
            currency: "EUR" | "USD" | "INR";
            /**
             * Format: int64
             * @description Amount in minor units (e.g. €12.50 = 1250). Always an integer.
             */
            value: number;
        };
        CreateGroupRequest: {
            /** @description Group name */
            name: string;
            /**
             * @description The group's immutable ISO-4217 currency (D7). Required.
             * @enum {string}
             */
            currency: "EUR" | "USD" | "INR";
        };
        GroupResponse: {
            /**
             * Format: uuid
             * @description Group ID
             */
            id: string;
            /** @description Group name */
            name: string;
            /**
             * Format: uuid
             * @description ID of the group admin
             */
            admin_user_id: string;
            /**
             * @description The group's immutable ISO-4217 currency (D7).
             * @enum {string}
             */
            currency: "EUR" | "USD" | "INR";
            /**
             * Format: date-time
             * @description Group creation timestamp
             */
            created_at: string;
        };
        /** @description A group the caller belongs to, enriched for the dashboard listing. The summary_balance is a glanceable figure computed from currently-posted approved ledger entries; it does NOT trigger allowance/EMI posting, so it may lag the authoritative per-group balance by the current month's machine-posted entries until the group is opened. */
        GroupSummaryResponse: {
            /**
             * Format: uuid
             * @description Group ID
             */
            id: string;
            /** @description Group name */
            name: string;
            /**
             * Format: uuid
             * @description ID of the group admin
             */
            admin_user_id: string;
            /**
             * @description The group's immutable ISO-4217 currency (D7).
             * @enum {string}
             */
            currency: "EUR" | "USD" | "INR";
            /**
             * Format: date-time
             * @description Group creation timestamp
             */
            created_at: string;
            /**
             * @description The caller's role in this group.
             * @enum {string}
             */
            role: "admin" | "member";
            /** @description Number of members in the group (includes the admin). */
            member_count: number;
            /** @description Role-dependent summary in the group's currency. For role=admin, the sum of all NON-admin members' balances (= total the admin owes members; typically >= 0). For role=member, the caller's OWN balance in this group (positive = earned/owed-to-them, negative = they owe the admin). Computed as Σ approved credits − Σ approved debits. A member never receives another member's figure. */
            summary_balance: components["schemas"]["Money"];
        };
        GroupDetailResponse: {
            /**
             * Format: uuid
             * @description Group ID
             */
            id: string;
            /** @description Group name */
            name: string;
            /**
             * Format: uuid
             * @description ID of the group admin
             */
            admin_user_id: string;
            /**
             * @description The group's immutable ISO-4217 currency (D7).
             * @enum {string}
             */
            currency: "EUR" | "USD" | "INR";
            /**
             * Format: date-time
             * @description Group creation timestamp
             */
            created_at: string;
            /** @description List of group members */
            members: components["schemas"]["MemberResponse"][];
            /** @description Number of chores in the group */
            chores_count: number;
        };
        MemberResponse: {
            /**
             * Format: uuid
             * @description User ID
             */
            user_id: string;
            /** @description User's full name */
            name: string;
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * @description User's role in the group
             * @enum {string}
             */
            role: "admin" | "member";
            /**
             * @description Whether this member has registered (can log in) or is a shadow the admin bookkeeps against.
             * @enum {string}
             */
            status: "shadow" | "registered";
            /**
             * Format: date-time
             * @description Timestamp when user joined the group
             */
            joined_at: string;
        };
        AddMemberRequest: {
            /**
             * Format: email
             * @description Email of the person to add. Case-insensitive matching is NOT required for this WP (the email column is plain TEXT UNIQUE); match is exact.
             */
            email: string;
            /** @description Display name. Used only when creating a new shadow user; ignored when the email already resolves to a user. */
            name: string;
        };
        InviteRequest: {
            /**
             * @description Number of days until invite expires
             * @default 7
             */
            expires_in_days: number;
        };
        InviteResponse: {
            /** @description Full invite URL */
            invite_url: string;
            /** @description Invite token */
            token: string;
            /**
             * Format: date-time
             * @description Expiration timestamp
             */
            expires_at: string;
        };
        JoinRequest: {
            /** @description Invite token */
            token: string;
        };
        CreateChoreRequest: {
            /** @description Chore name */
            name: string;
            /** @description Chore description */
            description?: string | null;
            /** @description Amount earned for completing the chore. value >= 1; currency must equal the group's. */
            amount: components["schemas"]["Money"];
        };
        UpdateChoreRequest: {
            /** @description Chore name */
            name?: string | null;
            /** @description Chore description */
            description?: string | null;
            /** @description Amount earned for completing the chore. value >= 1 when present; currency must equal the group's. */
            amount?: components["schemas"]["Money"] | null;
        };
        ChoreResponse: {
            /**
             * Format: uuid
             * @description Chore ID
             */
            id: string;
            /**
             * Format: uuid
             * @description Group ID
             */
            group_id: string;
            /** @description Chore name */
            name: string;
            /** @description Chore description */
            description?: string | null;
            /** @description Amount earned for completing the chore, in the group's currency. */
            amount: components["schemas"]["Money"];
            /** @description Whether this is a system-generated chore (e.g., Settlement) */
            is_system: boolean;
            /**
             * Format: date-time
             * @description Chore creation timestamp
             */
            created_at: string;
        };
        CreateLedgerRequest: {
            /**
             * @description Type of ledger entry. allowance/emi are machine-posted only and are rejected on this endpoint.
             * @enum {string}
             */
            entry_type: "chore" | "settlement" | "adjustment";
            /**
             * Format: uuid
             * @description Target user ID (admin may specify any member; member defaults to self)
             */
            user_id?: string | null;
            /**
             * Format: uuid
             * @description Chore ID (required when entry_type=chore; must be a non-system chore in this group)
             */
            chore_id?: string | null;
            /** @description Amount in the group's currency (value >= 1), required for settlement/adjustment; ignored for chore — chore config amount is used instead. When supplied, currency must equal the group's. */
            amount?: components["schemas"]["Money"] | null;
            /**
             * @description Direction (required for adjustment; server sets direction for chore and settlement)
             * @enum {string|null}
             */
            direction?: "credit" | "debit" | null;
            /** @description Optional note (recommended for adjustment to explain the reason) */
            note?: string | null;
        };
        LedgerResponse: {
            /**
             * Format: uuid
             * @description Ledger entry ID
             */
            id: string;
            /**
             * Format: uuid
             * @description Group ID
             */
            group_id: string;
            /**
             * Format: uuid
             * @description User whose balance is affected
             */
            user_id: string;
            /**
             * Format: uuid
             * @description Chore ID (null for settlement/adjustment/allowance/emi)
             */
            chore_id?: string | null;
            /** @description Amount in the group's currency. value is always positive — the direction field indicates credit/debit. */
            amount: components["schemas"]["Money"];
            /**
             * @description Entry status
             * @enum {string}
             */
            status: "approved" | "pending_approval" | "rejected";
            /**
             * @description Type of balance event
             * @enum {string}
             */
            entry_type: "chore" | "allowance" | "emi" | "settlement" | "adjustment";
            /**
             * @description Credit adds to balance; debit subtracts from balance
             * @enum {string}
             */
            direction: "credit" | "debit";
            /**
             * Format: uuid
             * @description Loan ID (set on emi entries; FK added in migration 011)
             */
            loan_id?: string | null;
            /** @description Month period in YYYY-MM format (set on allowance/emi entries) */
            period?: string | null;
            /** @description Optional free-text note */
            note?: string | null;
            /**
             * Format: uuid
             * @description User who created the entry
             */
            created_by_user_id: string;
            /**
             * Format: uuid
             * @description User who approved or rejected the entry
             */
            decided_by?: string | null;
            /**
             * Format: date-time
             * @description When the entry was approved or rejected
             */
            decided_at?: string | null;
            /**
             * Format: date-time
             * @description Entry creation timestamp
             */
            created_at: string;
        };
        BalanceResponse: {
            /**
             * Format: uuid
             * @description User ID
             */
            user_id: string;
            /** @description User's full name */
            name: string;
            /** @description Sum of approved credits minus approved debits, in the group's currency. */
            balance: components["schemas"]["Money"];
        };
        SetAllowanceRequest: {
            /** @description Monthly pocket money in the group's currency. value >= 0 (0 pauses the allowance); currency must equal the group's. */
            amount: components["schemas"]["Money"];
            /** @description Month this amount takes effect (YYYY-MM). Defaults to the current month. */
            effective_from?: string | null;
        };
        AllowanceResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            user_id: string;
            /** @description Monthly pocket money in the group's currency; value 0 = paused. */
            amount: components["schemas"]["Money"];
            /** @description YYYY-MM */
            effective_from: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateLoanRequest: {
            /**
             * Format: uuid
             * @description Borrower. Required when the admin creates a pre-approved loan; ignored/self for member requests.
             */
            user_id?: string | null;
            /** @description Loan principal in the group's currency. value >= 1; currency must equal the group's. */
            principal: components["schemas"]["Money"];
            /** @description Number of monthly installments. > 0. */
            installments: number;
            note?: string | null;
        };
        /** @description Optional overrides applied before approval; emi_amount is recomputed. */
        ApproveLoanRequest: {
            /** @description Optional principal override in the group's currency. value >= 1 when present; currency must equal the group's. */
            principal?: components["schemas"]["Money"] | null;
            installments?: number | null;
        };
        LoanResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            user_id: string;
            /** @description Loan principal in the group's currency. */
            principal: components["schemas"]["Money"];
            installments: number;
            /** @description ceil(principal/installments), in the group's currency. */
            emi_amount: components["schemas"]["Money"];
            /** @description YYYY-MM; null until active */
            start_period?: string | null;
            /** @enum {string} */
            status: "requested" | "active" | "rejected" | "closed";
            note?: string | null;
            /** Format: date-time */
            requested_at: string;
            /** Format: uuid */
            decided_by?: string | null;
            /** Format: date-time */
            decided_at?: string | null;
            /** @description Count of posted EMI entries */
            installments_posted: number;
            /** @description principal − Σ posted EMIs, in the group's currency. */
            outstanding: components["schemas"]["Money"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created and logged in (returns token + user, same as login) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Bad request (validation error or email already exists) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Bad request (validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully (no content) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed body or new password too short (min 6) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated (missing/invalid token) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Current password is incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of the user's groups, each enriched with role, member count, and a role-dependent summary balance for the dashboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSummaryResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Bad request (validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group details retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetailResponse"];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addMemberByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Invalid group ID or malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the group admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The target email is already a member of this group */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
                /** @description ID of the member to remove (equal to the caller for "leave") */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed / left successfully (no content) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid group ID or user ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A non-admin member may only remove themselves */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Target user is not a member of this group */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Removal blocked — the target is the group admin, or their balance is not zero, or they have an active/pending loan. The error message is human-readable and states which. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Invite created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can create invites */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    joinGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successfully joined group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Invalid token, token expired, or already a member */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of chores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreResponse"][];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createChore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChoreRequest"];
            };
        };
        responses: {
            /** @description Chore created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreResponse"];
                };
            };
            /** @description Bad request (validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can create chores */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteChore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chore ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chore deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid chore ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can delete chores or cannot delete system chore */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Chore not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateChore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chore ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChoreRequest"];
            };
        };
        responses: {
            /** @description Chore updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoreResponse"];
                };
            };
            /** @description Bad request (validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can update chores or cannot modify system chore */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Chore not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLedger: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: "approved" | "pending_approval" | "rejected";
                /** @description Filter by user ID (admin only) */
                user_id?: string;
                /** @description Filter by entry type */
                type?: "chore" | "allowance" | "emi" | "settlement" | "adjustment";
                /** @description Filter by period (YYYY-MM format) */
                period?: string;
            };
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ledger entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"][];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group, or a member requesting another member's data (D6). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLedgerRequest"];
            };
        };
        responses: {
            /** @description Ledger entry created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"];
                };
            };
            /** @description Bad request (validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Permission denied (e.g., only admin can create settlement entries) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approveLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ledger entry ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry approved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"];
                };
            };
            /** @description Entry is not pending approval */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can approve entries */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rejectLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ledger entry ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry rejected successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"];
                };
            };
            /** @description Entry is not pending approval */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Only group admin can reject entries */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of member balances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"][];
                };
            };
            /** @description Invalid group ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAllowances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allowance rows (empty array when none configured) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowanceResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setAllowance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: string;
                /** @description Target member's user ID (must be a member, not the admin) */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAllowanceRequest"];
            };
        };
        responses: {
            /** @description Allowance set or updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowanceResponse"];
                };
            };
            /** @description Validation error (negative amount, invalid period, targeting admin) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the group admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Target user is not a member of this group */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLoans: {
        parameters: {
            query?: {
                /** @description Filter by borrower user ID (admin only) */
                user_id?: string | null;
                /** @description Filter by loan status */
                status?: "requested" | "active" | "rejected" | "closed" | null;
            };
            header?: never;
            path: {
                /** @description Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loan list (empty array when none) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"][];
                };
            };
            /** @description Invalid filter parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group, or a member requesting another member's data (D6). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanRequest"];
            };
        };
        responses: {
            /** @description Loan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Target user not a member (admin-created loans) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approveLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Loan ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveLoanRequest"];
            };
        };
        responses: {
            /** @description Loan approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the group admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan is not pending approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rejectLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Loan ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loan rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the group admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan is not pending approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    closeLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Loan ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loan closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the group admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Loan is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
